[workspace]
resolver = "3"
members = [
  "videoson",
  "videoson-core",
  "videoson-common",
  "videoson-codec-h264",
  "videoson-codec-h265",
  "videoson-codec-vp8",
  "videoson-codec-vp9",
  "videoson-codec-rav1d",
  "videoson-format-ivf",
  "testbench",
]

[workspace.package]
version = "0.5.1"
edition = "2024"
license = "MPL-2.0"
repository = "https://github.com/mlm-games/videoson"
rust-version = "1.93"

[workspace.dependencies]
videoson-core = { path = "videoson-core", version = "0", default-features = false }
videoson-common = { path = "videoson-common", version = "0", default-features = false }
videoson-codec-h264 = { path = "videoson-codec-h264", version = "0", default-features = false }
videoson-codec-h265 = { path = "videoson-codec-h265", version = "0", default-features = false }
videoson-codec-vp8 = { path = "videoson-codec-vp8", version = "0", default-features = false }
videoson-codec-vp9 = { path = "videoson-codec-vp9", version = "0", default-features = false }
videoson-codec-rav1d = { path = "videoson-codec-rav1d", version = "0" }
videoson-format-ivf = { path = "videoson-format-ivf", version = "0", default-features = false }

rust_h264 = { version = "0.4.0" }
oxideav-h265 = { version = "0.0.10", default-features = false }
oxideav-vp8 = { version = "0.2.7", default-features = false }
oxideav-vp9 = { version = "0.0.13", default-features = false }
oxideav-core = { version = "0.1.35", default-features = false }
oxideav-bitstream = { version = "0.0.2", default-features = false }
rav1d-safe = { version = "0.6" }

anyhow = { version = "1" }
less-avc = { version = "0.1.5" }
