[package]
name = "videoson-codec-h265"
version.workspace = true
edition.workspace = true
license.workspace = true
repository.workspace = true
description = "H.265/HEVC decoder for videoson (via oxideav-h265)"
rust-version.workspace = true

[features]
default = ["std"]
std = ["videoson-core/std", "videoson-common/std"]

[dependencies]
videoson-core.workspace = true
videoson-common.workspace = true
oxideav-core.workspace = true

oxideav-h265.workspace = true
